### ISSUE TITLE
Exception in RimWorld.ThinkNode_Priority_GetJoy TryIssueJobPackage: System.ArgumentException: Value does not fall within the expected range.

### ISSUE THREAD

**Issue by potjeh** [catgirlfighter/RimWorld_CommonSense#23]
Log: https://pastebin.com/XpJ7Yj8y

If you need anything more, just say and I'll get it.

Have a nice day!

**Comment by potjeh** [comment]
P.S. The paste expires in a month.

**Comment by catgirlfighter** [comment]
I guess that's a compatibility issue with Better Pawn Control. Looking for outdoors scenario tries to find a suitable joygiver, stumbles on a takedrug one, and something goes bad from there. CS uses copied vanilla code to search for joygivers, but Pawn Control most likely changes how vanilla code used to work, so CS variant probably doesn't work as expected because of this.
It would be easier for me to do something about it if you attached a saved game right when issue is appearing. And if you need a work around - try disabling outdoors satisfaction.

**Comment by potjeh** [comment]
I finally opened up the dev console to see what's pausing the game (it's not a game breaker but I'd be interested in the problem, so I assumed you might also be). I just made a save and I'll also compress the mod dir so you don't have to mess with those. Gimme a moment.

**Comment by potjeh** [comment]
The save is also in there.
https://drive.google.com/file/d/14zzyKfWFo1ZNGuXJkuasftTyCGHOT61o/view?usp=sharing

**Comment by catgirlfighter** [comment]
Downloaded. I'll check it later.

**Comment by catgirlfighter** [comment]
Made a fix, now craving for outdoors skips erroneous jobs and tries to find the one that works. But it only made so error now happens without Common Sense involved, because CS algorithm returns control to base behavior. Can't do anything about that.

**Comment by potjeh** [comment]
Thank you kindly. Applying the new version... now.
