### ISSUE TITLE
Request: add random ingredients to non-crafted meals option that doesn't just choose neutral ingredients

### ISSUE THREAD

**Issue by mikester112** [catgirlfighter/RimWorld_CommonSense#29]
Just thought it would be funny if people started dropping meals with human meat in it.

**Comment by catgirlfighter** [comment]
Yeah, I left them out on purpose, because it changes the game in inconvenient way, and that's not the purpose of the mod. Plus it would be adding weird ingredients just for the heck of it, because I can't tell, for whom they're generated. I don't think that's a good idea because there's plenty of people that don't even read into options and just enable all of them, because mod doesn't have any "pranky" options, adding something like that would only generate questions and complaints that would require explaining, why would I add an option that actually "doesn't make sense".

**Comment by mikester112** [comment]
Fair enough.
