### ISSUE TITLE
Food taking priority.

### ISSUE THREAD

**Issue by Lak4CYUT** [catgirlfighter/RimWorld_CommonSense#43]
I have a scenario, it look like **not make sense** for me.. XD
I am like to know whether this mod can solve it.

I have a restaurant and there is a door combine to my big freezer room. I keep a lot food in my restaurant (in a small refrigerator, come from another MOD, or put on floor)
But my people often try to take food from freezer room and go back to restaurant, eating at the table, without to pick up food from the restaurant.

I mean, people should get their food from the nearest place if all the food is no longer rotten.
If it can be done, I will very grateful. Thanks.

**Comment by catgirlfighter** [comment]
Pawns prioritize distance to the food a lot. And distance to the ROOM is secondary. It happens because after finding closest item scanner scans around just a little more and picks from whatever is nearby (based on some priority rules), to cut on scanning time losses.
There is a mod for that btw.
https://steamcommunity.com/sharedfiles/filedetails/?id=1339148170

**Comment by Lak4CYUT** [comment]
wow, thanks. Let me check it.
